server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://115.28.145.220:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: Q123456p
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: org.spring.springboot.domain
  mapper-locations: classpath:mapper/*.xml
## s数据源的相关配置

# mybatis 配置文件的相关