# 先配置数据源
mybatis:
  typeAliasesPackage: com.ryan.springboot.domain
  mapperLocations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://115.28.145.220:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: Q123456p
    driver-class-name: com.mysql.jdbc.Driver
